BEGIN TRANSACTION;

INSERT INTO regions(id, name) VALUES(1, "Other");
INSERT INTO regions(id, name) VALUES(2, "Annapolis Valley");
INSERT INTO regions(id, name) VALUES(3, "Central Newfoundland");
INSERT INTO regions(id, name) VALUES(4, "Chignecto Central West");
INSERT INTO regions(id, name) VALUES(5, "Chignecto East");
INSERT INTO regions(id, name) VALUES(6, "Eastern Newfoundland");
INSERT INTO regions(id, name) VALUES(8, "New Brunswick");
INSERT INTO regions(id, name) VALUES(9, "Prince Edward Island");
INSERT INTO regions(id, name) VALUES(10, "South Shore");
INSERT INTO regions(id, name) VALUES(11, "Strait");
INSERT INTO regions(id, name) VALUES(12, "Tri-County");
INSERT INTO regions(id, name) VALUES(13, "Western Newfoundland");
INSERT INTO regions(id, name) VALUES(15, "Beaufort-Delta");
INSERT INTO regions(id, name) VALUES(16, "Carlton Trail");
INSERT INTO regions(id, name) VALUES(17, "Fransaskoise");
INSERT INTO regions(id, name) VALUES(19, "Kivalliq");
INSERT INTO regions(id, name) VALUES(20, "Leader");
INSERT INTO regions(id, name) VALUES(21, "Manitoba Schools Science Symposium");
INSERT INTO regions(id, name) VALUES(22, "Northern Manitoba");
INSERT INTO regions(id, name) VALUES(23, "Northern Saskatchewan");
INSERT INTO regions(id, name) VALUES(24, "Northwest Saskatchewan");
INSERT INTO regions(id, name) VALUES(25, "Parkland");
INSERT INTO regions(id, name) VALUES(26, "Prince Albert & Northeast Saskatchewan");
INSERT INTO regions(id, name) VALUES(27, "Qu'Appelle Valley");
INSERT INTO regions(id, name) VALUES(28, "Regina");
INSERT INTO regions(id, name) VALUES(29, "River East Transcona");
INSERT INTO regions(id, name) VALUES(30, "Sahtu");
INSERT INTO regions(id, name) VALUES(31, "Saskatoon");
INSERT INTO regions(id, name) VALUES(32, "Southeast Saskatchewan");
INSERT INTO regions(id, name) VALUES(33, "St. James-Assiniboia");
INSERT INTO regions(id, name) VALUES(34, "Saskatchewan Chinook");
INSERT INTO regions(id, name) VALUES(35, "Western Manitoba");
INSERT INTO regions(id, name) VALUES(36, "Winnipeg Schools");
INSERT INTO regions(id, name) VALUES(38, "Algoma Rotary");
INSERT INTO regions(id, name) VALUES(39, "East Parry Sound");
INSERT INTO regions(id, name) VALUES(40, "Frontenac, Lennox & Addington");
INSERT INTO regions(id, name) VALUES(41, "North Bay");
INSERT INTO regions(id, name) VALUES(42, "North Channel");
INSERT INTO regions(id, name) VALUES(43, "Northwestern Ontario");
INSERT INTO regions(id, name) VALUES(44, "Ottawa");
INSERT INTO regions(id, name) VALUES(45, "Peterborough");
INSERT INTO regions(id, name) VALUES(46, "Quinte");
INSERT INTO regions(id, name) VALUES(47, "Renfrew County");
INSERT INTO regions(id, name) VALUES(48, "Rideau-St. Lawrence");
INSERT INTO regions(id, name) VALUES(49, "Sudbury");
INSERT INTO regions(id, name) VALUES(50, "Sunset Country");
INSERT INTO regions(id, name) VALUES(51, "Timmins");
INSERT INTO regions(id, name) VALUES(52, "United Counties");
INSERT INTO regions(id, name) VALUES(53, "Avon Maitland-Huron Perth");
INSERT INTO regions(id, name) VALUES(54, "Bay Area");
INSERT INTO regions(id, name) VALUES(55, "Bluewater");
INSERT INTO regions(id, name) VALUES(56, "Chatham-Kent");
INSERT INTO regions(id, name) VALUES(58, "Lambton County");
INSERT INTO regions(id, name) VALUES(59, "London District");
INSERT INTO regions(id, name) VALUES(60, "Niagara");
INSERT INTO regions(id, name) VALUES(61, "Peel");
INSERT INTO regions(id, name) VALUES(62, "Simcoe County");
INSERT INTO regions(id, name) VALUES(63, "Toronto");
INSERT INTO regions(id, name) VALUES(64, "Victoria County");
INSERT INTO regions(id, name) VALUES(65, "Waterloo-Wellington");
INSERT INTO regions(id, name) VALUES(66, "Windsor");
INSERT INTO regions(id, name) VALUES(67, "York");
INSERT INTO regions(id, name) VALUES(68, "Abitibi-Témiscamingue");
INSERT INTO regions(id, name) VALUES(69, "Côte-Nord");
INSERT INTO regions(id, name) VALUES(70, "Est du Québec");
INSERT INTO regions(id, name) VALUES(71, "Estrie");
INSERT INTO regions(id, name) VALUES(72, "Mauricie, Centre-du-Québec");
INSERT INTO regions(id, name) VALUES(73, "Montérégie");
INSERT INTO regions(id, name) VALUES(74, "Montreal");
INSERT INTO regions(id, name) VALUES(75, "Montréal CLS");
INSERT INTO regions(id, name) VALUES(76, "Outaouais");
INSERT INTO regions(id, name) VALUES(77, "Québec et Chaudière-Appalaches");
INSERT INTO regions(id, name) VALUES(78, "Rive-Nord");
INSERT INTO regions(id, name) VALUES(79, "Saguenay-Lac Saint-Jean");
INSERT INTO regions(id, name) VALUES(80, "Alberta Central East");
INSERT INTO regions(id, name) VALUES(81, "Calgary Youth");
INSERT INTO regions(id, name) VALUES(82, "Cariboo Mainline");
INSERT INTO regions(id, name) VALUES(83, "Central Alberta");
INSERT INTO regions(id, name) VALUES(84, "Central Interior British Columbia");
INSERT INTO regions(id, name) VALUES(85, "Central Okanagan");
INSERT INTO regions(id, name) VALUES(86, "Chinook Country");
INSERT INTO regions(id, name) VALUES(87, "East Kootenay");
INSERT INTO regions(id, name) VALUES(88, "Edmonton");
INSERT INTO regions(id, name) VALUES(89, "Fraser Valley");
INSERT INTO regions(id, name) VALUES(90, "Greater Vancouver");
INSERT INTO regions(id, name) VALUES(91, "Kiwanis Southeast Alberta");
INSERT INTO regions(id, name) VALUES(93, "North Okanagan/Shuswap");
INSERT INTO regions(id, name) VALUES(94, "Northern British Columbia");
INSERT INTO regions(id, name) VALUES(95, "Northern Vancouver Island");
INSERT INTO regions(id, name) VALUES(96, "Pacific Northwest");
INSERT INTO regions(id, name) VALUES(97, "Peace Country");
INSERT INTO regions(id, name) VALUES(98, "Vancouver Island");
INSERT INTO regions(id, name) VALUES(99, "West Kootenay & Boundary");
INSERT INTO regions(id, name) VALUES(100, "Yukon/Stikine");
INSERT INTO regions(id, name) VALUES(101, "Australia");
INSERT INTO regions(id, name) VALUES(104, "Sweden");
INSERT INTO regions(id, name) VALUES(105, "Taiwan, R.O.C.");
INSERT INTO regions(id, name) VALUES(106, "CDLS - Province du Québec");
INSERT INTO regions(id, name) VALUES(107, "Cape Breton");
INSERT INTO regions(id, name) VALUES(110, "Kitikmeot");
INSERT INTO regions(id, name) VALUES(111, "Manitoba First Nations");
INSERT INTO regions(id, name) VALUES(112, "Qikiqtani");
INSERT INTO regions(id, name) VALUES(113, "Durham");
INSERT INTO regions(id, name) VALUES(114, "Halifax");
INSERT INTO regions(id, name) VALUES(115, "Lethbridge");
INSERT INTO regions(id, name) VALUES(116, "Yellowknife");
INSERT INTO regions(id, name) VALUES(117, "Conseil scolaire acadien provincial");
INSERT INTO regions(id, name) VALUES(118, "Mi'kma'q First Nation");
INSERT INTO regions(id, name) VALUES(119, "Aboriginal Québec Autochtone");
INSERT INTO regions(id, name) VALUES(120, "Labrador");
INSERT INTO regions(id, name) VALUES(121, "South Fraser");
INSERT INTO regions(id, name) VALUES(122, "Wood Buffalo");
INSERT INTO regions(id, name) VALUES(123, "Canadian Rockies");
INSERT INTO regions(id, name) VALUES(124, "Fundy");
INSERT INTO regions(id, name) VALUES(125, "River Valley");
INSERT INTO regions(id, name) VALUES(126, "Chaleur");
INSERT INTO regions(id, name) VALUES(127, "Mexico");
INSERT INTO regions(id, name) VALUES(128, "Prairie Valley");
INSERT INTO regions(id, name) VALUES(129, "Districts francophones du Nouveau-Brunswick");
INSERT INTO regions(id, name) VALUES(130, "Chignecto West");
INSERT INTO regions(id, name) VALUES(131, "Saskatchewan First Nations");
INSERT INTO regions(id, name) VALUES(132, "Kawartha");
INSERT INTO regions(id, name) VALUES(133, "Southeast Alberta");
INSERT INTO regions(id, name) VALUES(134, "Thames Valley");
INSERT INTO regions(id, name) VALUES(136, "Frontier Schools");
INSERT INTO regions(id, name) VALUES(137, "4-H Canada");
INSERT INTO regions(id, name) VALUES(138, "South Slave");
INSERT INTO regions(id, name) VALUES(139, "India");
INSERT INTO regions(id, name) VALUES(140, "Turkey");
INSERT INTO regions(id, name) VALUES(141, "St. Maarten");
INSERT INTO regions(id, name) VALUES(142, "Réseau Technoscience");
INSERT INTO regions(id, name) VALUES(143, "Island Lakes");
INSERT INTO regions(id, name) VALUES(144, "Bison");
INSERT INTO regions(id, name) VALUES(145, "Montréal RM");

COMMIT;
